Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
Internal Server Error: /api/ngafid/unique_labels/
Traceback (most recent call last):
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Decartes\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /api/ngafid/unique_labels/ HTTP/1.1" 500 79554
